ALTER TABLE "Provider"
ADD COLUMN "integrationType" TEXT NOT NULL DEFAULT 'DEMO',
ADD COLUMN "bookingUrl" TEXT,
ADD COLUMN "cities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "rideTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];